trigger: none

pool:
  name: 'DCO-HighQ-Platform-N'

resources:
  repositories:
    - repository: ZurichDeploy
      type: git
      name: Zurich.Deploy

variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- template: ../Variables/connector-variables-Shared.yml   

# build number in format of Zurich-Connector.dev.20200204.1
name: $(BuildDefinitionName).$(SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  jobs:
    - job: 'Build'
      displayName: 'Connectors Build'
      steps:
        - checkout: self
        - checkout: ZurichDeploy
        - template: Templates\V2\ZurichDeploy-BuildWebAPI.yml@ZurichDeploy
          parameters:
            projectName: ${{ variables.projectName }}
            azureAdClientSecret: $(azureAdClientSecret)
            environmentName: ci