parameters:
- name: apiId 
  type: string
- name: apimName
  type: string
- name: apimResourceGroup
  type: string 
- name: apiVersion 
  type: string
- name: environmentName
  type: string
- name: groups
  type: string
- name: productDescription
  type: string
- name: productName
  type: string
- name: resourceGroup
  type: string
- name: connectorServiceName
  type: string
- name: subscriptionName
  type: string
- name: swaggerEndpoint
  type: string

jobs:
  - job: 'UpdateApim'
    displayName: 'Update Apim Connector Product'
    steps:
      - checkout: self
      - checkout: ZurichDeploy
      - task: AzurePowerShell@5
        displayName: 'Setup APIM with Docs'
        inputs:
          azureSubscription: ${{ parameters.subscriptionName }}
          ScriptPath: '$(Build.SourcesDirectory)/Zurich.Deploy/Scripts/AddProductToAPIM.ps1'
          ScriptArguments: '-resourceGroupName "${{parameters.resourceGroup}}" -ApimResourceGroupName "${{parameters.apimResourceGroup}}" -ApimName "${{parameters.apimName}}" -env "${{parameters.environmentName}}" -swaggerEndpoint "${{parameters.swaggerEndpoint}}" -apiId "${{parameters.apiId}}" -appServiceName "${{parameters.connectorServiceName}}" -productName "${{parameters.productName}}" -productDescription "${{parameters.productDescription}}" -groups ${{parameters.groups}}  -apiVersion "${{parameters.apiVersion}}" -ApimProductPolicyFilePath "$(Build.SourcesDirectory)/Zurich.Connector.Deploy/Config/${{parameters.environmentName}}/ConnectorAPIMPolicy.xml"'
          azurePowerShellVersion: LatestVersion